from django.urls import path
from . import views

urlpatterns = [
    path('waitlist/', views.AffiliateMail, name='waitlist'),
    path('offer-expiry/', views.OfferExpiryMail, name='offer-expiry/'),
    path('offer-expired/', views.OfferExpiredMail, name='offer-expired/'),
    path('new-partner/', views.NewPartnerMail, name='new-partner'),
    path('new-on-the-network/', views.NewOnTheNetworkMail,
         name='new-on-the-network'),
    path('customer-retained/', views.CustomerRetained, name='customer-retained'),
    path('campaign-live/', views.CampaignLive, name='campaign-live'),
    path('sniper-live/', views.SniperLive, name='sniper-live'),
    path('sniper-resumed/', views.SniperResumed, name='sniper-resumed'),
    path('sniper-stopped/', views.SniperStopped, name='sniper-stopped'),
    path('sniper-admin-resumed/', views.SniperAdminResumed,
         name='sniper-admin-resumed'),
    path('sniper-admin-stopped/', views.SniperAdminStopped,
         name='sniper-admin-stopped'),
    path('semperfi-live/', views.SemperFiLive, name='semperfi-live'),
    path('semperfi-resumed/', views.SemperFiResumed, name='semperfi-resumed'),
    path('semperfi-stopped/', views.SemperFiStopped, name='semperfi-stopped'),
    path('semperfi-admin-resumed/', views.SemperFiAdminResumed,
         name='semperfi-admin-resumed'),
    path('semperfi-admin-stopped/', views.SemperFiAdminStopped,
         name='semperfi-admin-stopped'),
    path('infiniti-live/', views.InfinitiLive, name='infiniti-live'),
    path('infiniti-resumed/', views.InfinitiResumed, name='infiniti-resumed'),
    path('infiniti-stopped/', views.InfinitiStopped, name='infiniti-stopped'),
    path('infiniti-admin-resumed/', views.InfinitiAdminResumed,
         name='infiniti-admin-resumed'),
    path('infiniti-admin-stopped/', views.InfinitiAdminStopped,
         name='infiniti-admin-stopped'),
    path('added-to-inner-xircl/', views.AddedToInnerXircl,
         name='added-to-inner-xircl'),
    path('inner-xircl-expiring/', views.InnerXirclExpiring,
         name='inner-xircl-expiring'),
    path('inner-xircl-expired/', views.InnerXirclExpired,
         name='inner-xircl-expired'),
    path('new-customer-acquired/', views.NewCustomerAcquired,
         name='new-customer-acquired'),
    path('merchant-signup/', views.MerchantSignup, name='merchant-signup'),
]
