# Generated by Django 3.1.2 on 2023-07-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
