# Generated by Django 3.1.2 on 2023-07-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_todo_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_expired_value',
            field=models.BooleanField(default=False),
        ),
    ]
