# Generated by Django 3.1.2 on 2023-07-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_todo_is_expired_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_expired_value',
            field=models.BooleanField(),
        ),
    ]
