# Generated by Django 3.1.2 on 2023-08-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230731_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_expired_value',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
