# Generated by Django 3.1.2 on 2023-08-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230801_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
            ],
        ),
    ]
